<?php namespace Model\Ci;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Sessions extends ORM {
	
	public $primary_key = 'session_id';

	function _init()
	{
		self::$fields = array(
			'session_id' => ORM::field('char[40]'),
			'ip_address' => ORM::field('char[16]'),
			'user_agent' => ORM::field('char[50]'),
			'last_activity' => ORM::field('int[10]'),
			'user_data' => ORM::field('string'),
		);

	}
}