language: php
php: 
  - 5.3
  
env: DB=mysql

#whitelist
branches:
  only:
    -master

# install the database
before_script:
  - mysql -e "CREATE DATABASE IF NOT EXISTS grades_test;"
  - pear channel-discover pear.phpunit.de
  - pear install phpunit/PHPUnit
  - pear channel-discover pear.php-tools.net
  - pear install pat/vfsStream-alpha

# run the unit tests
script:
  - phpunit --configuration tests/mysql.travis.xml
