# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # aliased to 5.3.10
  - 5.3.10


# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - mysql -e "create database IF NOT EXISTS grades;" -uroot; 
  - mysql -uroot grades < /var/www/pagoda/db_fixtures.sql;

