<?php defined('BASEPATH') OR exit('No direct script access allowed');

/* This basic migration has been auto-generated by the Gas ORM */

class Migration_groups extends CI_Migration {

	public function up()
	{
		$this->dbforge->add_field(array(
			'id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'title' => array(
				'type' => 'VARCHAR',
				'constraint' => 20,
			),
			'description' => array(
				'type' => 'VARCHAR',
				'constraint' => 100,
			),
		));

		$this->dbforge->add_key('id', TRUE);

		$this->dbforge->create_table('groups', TRUE);
	}

	public function down()
	{
		$this->dbforge->drop_table('groups');
	}
}