<?php defined('BASEPATH') OR exit('No direct script access allowed');

/* This basic migration has been auto-generated by the Gas ORM */

class Migration_subject extends CI_Migration {

	public function up()
	{
		$this->dbforge->add_field(array(
			'id' => array(
				'type' => 'INT',
				'constraint' => 10,
			),
			'user_id' => array(
				'type' => 'INT',
				'constraint' => 10,
			),
			'code' => array(
				'type' => 'VARCHAR',
				'constraint' => 32,
			),
			'title' => array(
				'type' => 'VARCHAR',
				'constraint' => 255,
			),
			'notes' => array(
				'type' => 'TEXT',
				'constraint' => 0,
			),
			'deleted' => array(
				'type' => 'TINYINT',
				'constraint' => 1,
			),
			'created_on' => array(
				'type' => 'DATETIME',
				'constraint' => 0,
			),
			'modified_on' => array(
				'type' => 'DATETIME',
				'constraint' => 0,
			),
		));

		$this->dbforge->add_key('id', TRUE);

		$this->dbforge->create_table('subject', TRUE);
	}

	public function down()
	{
		$this->dbforge->drop_table('subject');
	}
}