<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Coursework extends ORM {
	
	public $primary_key = 'id';
	
	/**
	 * The number of days ahead to alert a user about coursework
	 */
	const STANDARD_ALERT_DAYS = 7;
	
	function _init()
	{
			
		self::$relationships = array (
			'subject' 		=> 		ORM::belongs_to('\\Model\\Subject'),
			'user'			=>		ORM::belongs_to('\\Model\\User'),
			'status'		=>		ORM::belongs_to('\\Model\\Status'),
		);		
		
		self::$fields = array(
			'id' 			=> 		ORM::field('auto[10]'),
			'users_id' 		=> 		ORM::field('int[10]'),
			'subject_id' 	=> 		ORM::field('int[10]'),
			'title' 		=> 		ORM::field('char[255]', array('trim','xss_clean','max_length[255]','required','strip_tags')),
			'due_date'		=>		ORM::field('date', array('valid_date')),
			'alert_sent'	=>		ORM::field('int[1]'),
			'status_id'		=> 		ORM::field('int[10]'),
			'notes' 		=> 		ORM::field('string', array('trim','xss_clean','strip_tags')),
			'score' 		=> 		ORM::field('int[3]', array('max_length[3]','greater_than[-1]','less_than[101]')),
			'weighting' 	=> 		ORM::field('int[3]', array('max_length[3]','greater_than[-1]','less_than[101]')),
			'deleted' 		=> 		ORM::field('numeric[1]'),
			'created_on' 	=> 		ORM::field('datetime'),
			'modified_on' 	=> 		ORM::field('datetime'),
		);
		
		$this->ts_fields = array('modified_on','[created_on]');

	}
}
