<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Profile extends ORM {
	
	public $primary_key = 'id';
	
	function _init()
	{
		
		self::$relationships = array (
			'user'			=>	 	ORM::belongs_to('\\Model\\User')
		);
		
		self::$fields = array(
			'id' 			=> 		ORM::field('auto[10]'),
			'users_id' 		=> 		ORM::field('int[10]'),
			'first_name'	=> 		ORM::field('char[255]'),
			'last_name'		=> 		ORM::field('char[255]'),
			'default_course'=> 		ORM::field('int[11]'),
			'first_login'	=>		ORM::field('int[1]'),
			'emails_allowed'=>		ORM::field('int[1]'),
			'unsubscribe_code' =>	ORM::field('char[23]'),
			'created_on'	=> 		ORM::field('datetime'),
			'modified_on' 	=> 		ORM::field('datetime'),
		);
		
		$this->ts_fields = array ('modified_on','[created_on]');

	}
}
