<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Status extends ORM {
	
	public $primary_key = 'id';
	
	// declare the constants
	const NONE = 1;
	const STARTED = 2;
	const DRAFTED = 3;
	const COMPLETED = 4;
	const HANDED_IN = 5;
	const RETURNED = 6;
	const CLOSED = 7; 
	
	function _init()
	{
			
		self::$relationships = array (
			'coursework'	=> 		ORM::has_many('\\Model\\Coursework'),
		);		
		
		self::$fields = array(
			'id' 			=> 		ORM::field('auto[10]'),
			'title' 		=> 		ORM::field('char[255]'),
		);
		
		$this->ts_fields = array('modified_on','[created_on]');

	}
}
