<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Status extends ORM {
	
	public $primary_key = 'id';
	
	function _init()
	{
			
		self::$relationships = array (
			'coursework'	=> 		ORM::has_many('\\Model\\Coursework'),
		);		
		
		self::$fields = array(
			'id' 			=> 		ORM::field('auto[10]'),
			'title' 		=> 		ORM::field('char[255]'),
		);
		
		$this->ts_fields = array('modified_on','[created_on]');

	}
}
