<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Subject extends ORM {
	
	public $primary_key = 'id';

	function _init()
	{
		self::$fields = array(
			'id' => ORM::field('auto[10]'),
			'user_id' => ORM::field('int[10]'),
			'code' => ORM::field('char[32]'),
			'title' => ORM::field('char[255]'),
			'notes' => ORM::field('string'),
			'deleted' => ORM::field('numeric[1]'),
			'created_on' => ORM::field('datetime'),
			'modified_on' => ORM::field('datetime'),
		);

	}
}