<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Users extends ORM {
	
	public $primary_key = 'id';

	function _init()
	{
		self::$fields = array(
			'id' => ORM::field('auto[11]'),
			'username' => ORM::field('char[255]'),
			'email' => ORM::field('char[255]'),
			'password' => ORM::field('char[255]'),
			'group_id' => ORM::field('int[11]'),
			'token' => ORM::field('char[255]'),
			'identifier' => ORM::field('char[255]'),
		);

	}
}